### PR TITLE
Do not error whole whole settlement if one price estimate fails

### LINKED ISSUE #395: Don't error full settlement if price of some tokens can't be determined
> 2021-03-18T11:48:39.695Z ERROR solver::driver: single run errored: failed estimating pricesCaused by:    no valid path found

Just noticed this in the alerts. We should continue with tokens for which we are able to get a price.

### PR DESCRIPTION
**Pull request by vkgnosis**
Fixes #395 

### Test Plan
Don't think a regression test is needed here as the function signature has changed to no longer return result.

### CODE REVIEW

File: solver/src/driver.rs [hunk 1]
```diff
@@ -94,30 +90,44 @@ impl Driver {
...
         tracing::debug!("starting single run");
-        let limit_orders = self
+        let mut limit_orders = self
             .orderbook
             .get_liquidity()
             .await
             .context("failed to get orderbook")?;
         tracing::debug!("got {} orders", limit_orders.len());
 
+        let estimated_prices = self.collect_estimated_prices(&limit_orders).await;
```
Comment (fleupold) [inline solver/src/driver.rs:117]: nanonit: Maybe log number of orders after the pruning?

**Review by fleupold — APPROVED** [review]
Thanks a lot for fixing!

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FlVBtp4SRW6rvDHf1b6%2Fgiphy-downsized-medium.gif&token=fix" data-gitmeme-token="fix"></a>

File: solver/src/driver.rs (hunk 1 above)
Comment (vkgnosis) [reply solver/src/driver.rs:117]: added
