### PR TITLE
Skip Inflight Orders in Single Run

### LINKED ISSUE #650: Settlement Reverts with `GPv2: order filled`
We have received quite a few alerts recently with Settlement simulations failing on 

```
contract call reverted with message: Some("GPv2: order filled")
```

This was uncovered last week and discussed in our weekly sync. The problem appears to be with the fact that orders which have been filled in a recent settlement have not yet been picked up by our event listener and thus, not yet flagged as having been matched. In the meantime our solver is already working on the next batch and attempts to use this order again.

It was mentioned that a reasonable avenue to mitigate this is to keep a temporary list of recently filled orders in memory (only as long as a single batch) for which the solver can filter these essentially pending/in flight already matched orders.

One additional piece of insight that would make this "hunch" a bit more apparent is if there were larger batches being settled with several orders for which we receive the alert with multiplicity. Unfortunately at this time our batches are usually limited to one or two trades so we have not seen a massive influx of identical alerts simultaneously.

### PR DESCRIPTION
**Pull request by bh2smith**
As proposed to solver the recent `GPv2: Order Filled` simulation failures, we can keep a set of inflight orders from the current settlement which is then passed onto the next single run. These orders are only ignored for at most one batch whether the transaction passes or fails. 

Not yet sure if this is the ideal/intended approach to this problem given that I noticed single run awaits transaction submission. I am guessing it only awaits confirmation of submission but not for the settlement to be mined.

In brief:

`single_run` accepts a set of inflight order ids which it passes onto the liquidity collector who filters these order by ID out of the orderbook. If a settlement is found, it stores the set of new inflight orders which it then returns to be passed into the next single run.

I am partially expecting to get some feedback along the lines of how this isn't directly connected to any check for transactions having been mined and when to actually clear the inflight orders. Perhaps single run could be executed multiple times without having any of its predecessors mined yet. In this case we would probably rather continue appending to inflight orders and only release when we know a corresponding settlement has been mined.

Once correct, this closes #650

### Test Plan
Plan to introduce a test once we have decided if this implementation is the best approach.

### CODE REVIEW

File: solver/src/driver.rs [hunk 1]
```diff
@@ -414,6 +421,14 @@ impl Driver {
 
             tracing::debug!("winning settlement: {:?}", settlement);
             self.submit_settlement(settlement.clone()).await;
+            inflight_orders = settlement
+                .settlement
+                .settlement
+                .trades()
+                .iter()
+                .map(|t| t.order.order_meta_data.uid)
```
Comment (fleupold) [inline solver/src/driver.rs:429]: We should probably only remove fully filled orders?

File: solver/src/liquidity_collector.rs [hunk 2]
```diff
@@ -4,17 +4,23 @@ use ethcontract::BlockNumber;
...
-    pub async fn get_liquidity(&self, at_block: BlockNumber) -> Result<Vec<Liquidity>> {
+    pub async fn get_liquidity(
+        &self,
+        at_block: BlockNumber,
+        excluded_orders: &HashSet<OrderUid>,
+    ) -> Result<Vec<Liquidity>> {
         let limit_orders = self
             .orderbook_api
-            .get_liquidity()
+            .get_liquidity(excluded_orders)
```
Comment (fleupold) [inline solver/src/liquidity_collector.rs:23]: nit: I would do the filtering here instead of leaking this logic further down the stack.

File: solver/src/driver.rs [hunk 3]
```diff
@@ -323,7 +327,10 @@ impl Driver {
             .await
     }
 
-    pub async fn single_run(&mut self) -> Result<()> {
+    pub async fn single_run(
+        &mut self,
+        inflight_orders: &HashSet<OrderUid>,
```
Comment (fleupold) [inline solver/src/driver.rs:332]: I'm not entirely sure the driver of this method should manage state about inflight orders. While this approach makes it very clear that inflight orders only stick around for the next run, I wonder if storing them as a field on the driver instance itself would be more contained.

File: e2e/tests/onchain_settlement.rs [hunk 4]
```diff
@@ -210,5 +210,5 @@ async fn onchain_settlement(web3: Web3) {
     assert!(orders.is_empty());
 
     // Drive again to ensure we can continue solution finding
-    driver.single_run().await.unwrap();
+    driver.single_run(&HashSet::new()).await.unwrap();
```
[the remark this answers is not in the document]
Comment (bh2smith) [reply e2e/tests/onchain_settlement.rs:213]: Yes, in particular I would think that this might suffice as a test for these changes, unless you think there should be a standalone test for it.

File: solver/src/liquidity_collector.rs (hunk 2 above)
Comment (bh2smith) [reply solver/src/liquidity_collector.rs:23]: I will have to check on this again, but noticed this method converts Orders to LimitOrder which no longer seem to have a UId. Will check back on this.

File: e2e/tests/onchain_settlement.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (bh2smith) [reply e2e/tests/onchain_settlement.rs]: Not needed anymore since we don't give it to a single run.

File: solver/src/driver.rs (hunk 1 above)
Comment (bh2smith) [reply solver/src/driver.rs:428]: Although if we do this, we still could run into the same problem trying to "over fill an order". I would think that missing at most one single run isn't so bad in this case.

Comment (fleupold) [reply solver/src/driver.rs:428]: > I would think that missing at most one single run isn't so bad in this case

It's essentially censoring this order and could potentially be used in an attack. Match some order partially as you know it won't be in the system next round. We could also store the remaining sell amount for those orders and update if they differ from what the orderbook sent us.

Comment (bh2smith) [reply solver/src/driver.rs:428]: Ok, so I am in the process of making this special consideration for partially fillable orders and stumbled upon an outstanding `TODO` in the code (particularly in `normalize_limit_order` which converts `Order` to `LimitOrder`

http://github.com/gnosis/gp-v2-services/blob/51d10253916e41cba150242cd874237bafb8a745/solver/src/liquidity/offchain_orderbook.rs#L60-L62

we see that it remains to discount previously executed amounts here. The question I would have it whether or not the solver takes the `OrderMetaData` into consideration when working with `LimitOrder`. 

More specifically if it would be a problem for settlement encoding to directly edit the `LimitOrder`'s buy and sell amount fields because we are possibly altering the content of the originally signed order. Of course it would probably make the most sense to directly update the `OrderMetaData` with the relevant inflight execution information, but the solver would at least need to cross check the `LimitOrder` it is given with the corresponding `Order`'s metadata (so not to overfill a partially filled solution). My worry here is that once converted to `LimitOrder` the Order data is dropped.

File: solver/src/driver.rs [hunk 5]
```diff
@@ -334,8 +337,13 @@ impl Driver {
             .as_u64();
         let liquidity = self
             .liquidity_collector
-            .get_liquidity(current_block_during_liquidity_fetch.into())
+            .get_liquidity(
+                current_block_during_liquidity_fetch.into(),
+                &self.inflight_orders,
+            )
             .await?;
+        // Reset the inflight orders after use.
```
Comment (fleupold) [inline solver/src/driver.rs:345]: This way they won't be reset if e.g. get_liquidity fails and returns early above. Maybe this needs to be written to a temp object and reset first thing in the run_single method?

File: solver/src/driver.rs [hunk 6]
```diff
@@ -414,6 +421,14 @@ impl Driver {
 
             tracing::debug!("winning settlement: {:?}", settlement);
             self.submit_settlement(settlement.clone()).await;
+            self.inflight_orders = settlement
```
Comment (fleupold) [inline solver/src/driver.rs:424]: Not entirely sure and no strong feeling, but maybe it would be less "leaky" to store the full trades in a hashset?

File: solver/src/liquidity/offchain_orderbook.rs [hunk 7]
```diff
@@ -4,21 +4,41 @@ use crate::settlement::SettlementEncoder;
...
     /// Returns a list of limit orders coming from the offchain orderbook API
-    pub async fn get_liquidity(&self) -> Result<Vec<LimitOrder>> {
+    pub async fn get_liquidity(&self, inflight_orders: &InflightOrders) -> Result<Vec<LimitOrder>> {
         Ok(self
             .get_orders()
             .await
             .context("failed to get orderbook")?
             .into_iter()
-            .map(|order| normalize_limit_order(order, self.get_native_token()))
+            .filter_map(|order| {
```
Comment (fleupold) [inline solver/src/liquidity/offchain_orderbook.rs:21]: Can we unit test this logic?

File: solver/src/driver.rs (hunk 6 above)
Comment (bh2smith) [reply solver/src/driver.rs:424]: Yes, although I might propose `HashMap<OrderUid, Trade>` so that we can easily search for `order_id` containment when flitering. Would this be a reasonable compromise?

Comment (bh2smith) [reply solver/src/driver.rs:424]: Given that we aren't actually handling this at the moment, I suppose we could get away without the `HashMap` for now.

File: solver/src/driver.rs [hunk 8]
```diff
@@ -414,6 +421,14 @@ impl Driver {
...
+                .settlement
+                .settlement
+                .trades()
+                .iter()
+                .map(|t| (t.order.order_meta_data.uid, t.executed_amount))
+                .collect::<HashMap<OrderUid, U256>>();
```
Comment (nlordell) [inline solver/src/driver.rs:430]: Why not use your fancy type alias?
```suggestion
                .collect::<InflightOrders>();
```

Also, I suspect the compiler would be able to figure this out on its own:
```suggestion
                .collect();
```

File: solver/src/driver.rs (hunk 6 above)
Comment (nlordell) [reply solver/src/driver.rs:424]: I would argue for a `HashSet<OrderUid>` since we don't really use the executed amount for now.

File: solver/src/liquidity/offchain_orderbook.rs [hunk 9]
```diff
@@ -4,21 +4,41 @@ use crate::settlement::SettlementEncoder;
...
+                        // order.order_meta_data.executed_buy_amount += executed_buy_amount;
+                    } else {
+                        // Fully filled, inflight orders are excluded from consideration
+                        return None;
+                    }
+                }
+                Some(normalize_limit_order(order, self.get_native_token()))
+            })
+            // .filter(|order| !excluded_orders.contains(&order.order_meta_data.uid))
+            // .map(|order| normalize_limit_order(order, self.get_native_token()))
```
Comment (nlordell) [inline solver/src/liquidity/offchain_orderbook.rs:41]: I expect these comments can be cleaned up.

File: solver/src/driver.rs (hunk 8 above)
Comment (bh2smith) [reply solver/src/driver.rs:430]: Actually it is going to be eliminated in favour of @fleupold's suggestion above. However in the future it might reappear as

`InflightTrades - HashMap<OrderUid, Trade>`

File: solver/src/driver.rs (hunk 5 above)
Comment (nlordell) [reply solver/src/driver.rs:345]: I would actually argue this shouldn't get cleared at all. It already get overwritten here: https://github.com/gnosis/gp-v2-services/blob/e0abb426d00af2fc7c4ff70d41ffbe3974d153fe/solver/src/driver.rs#L424-L430

File: solver/src/driver.rs (hunk 6 above)
Comment (nlordell) [reply solver/src/driver.rs:424]: I'm not fond of `HashSet<Trade>` because trade equality is brittle, and, at least for me, adds a lot of ambiguity to the code without looking around to fully understand the context. For example, imagine an order:
```rust
let order = Order { partially_fillable: true, ... };
let mut trades = HashSet::new();

trades.insert(Trade {
    order: order.clone(),
    sell_token_index: 0,
    buy_token_index: 1,
    executed_amount: 100.into(),
});
// What do you expect to happen here? Its the same order, so should it replace the existing trade in the
// hash set? The token indices are different, what does this mean and is it even possible here?
trades.insert(Trade {
    order: order.clone(),
    sell_token_index: 1,
    buy_token_index: 0,
    executed_amount: 50.into(),
});
```

File: solver/src/driver.rs (hunk 8 above)
Comment (nlordell) [reply solver/src/driver.rs:430]: I added comments :point_up:

**Comment by bh2smith** [comment]
Included some TODOs in the code with links to the related issue:

https://github.com/gnosis/gp-v2-services/issues/673

I will also flag this as a good first issue and see if @taminomara might be interested in checking it out!

File: solver/src/driver.rs (hunk 6 above)
Comment (nlordell) [reply solver/src/driver.rs]: The other issue I see with `HashMap<OrderUid, Trade>` is the ambiguity around trading a a partially fillable order multiple times in the same settlement. In that case `HashMap<OrderUid, Trade>` would not be enough as only one of the trades would be recorded.

I would either suggest `Vec<Trade>` and with the `.map().collect()` as you do here, or simply just use `HashSet<OrderUid>` for now, until we actually need trade data when filtering.

File: solver/src/liquidity/offchain_orderbook.rs [hunk 10]
```diff
@@ -28,6 +30,28 @@ struct OrderSettlementHandler {
     order: Order,
 }
 
+fn inflight_order_filter(order: Order, inflight_trades: &HashSet<Trade>) -> Option<Order> {
+    // TODO - could model inflight_trades as HashMap<OrderUid, Trade>
+    // https://github.com/gnosis/gp-v2-services/issues/673
+    // would avoid map-collect and make trade data accessible by id.
+    let inflight_trades_map = inflight_trades
```
Comment (nlordell) [inline solver/src/liquidity/offchain_orderbook.rs:37]: I'm not a huge fan of allocating a new map for every order being filtered just to do a more efficient search. You might as well just search linearly thought the `inflight_trades` as it would have the same runtime characteristic (`O(n)`) without having to allocate a map temporarily.

File: solver/src/liquidity/offchain_orderbook.rs [hunk 11]
```diff
@@ -28,6 +30,28 @@ struct OrderSettlementHandler {
...
+        .iter()
+        .map(|t| (t.order.order_meta_data.uid, t.clone()))
+        .collect::<HashMap<OrderUid, Trade>>();
+    if inflight_trades_map.contains_key(&order.order_meta_data.uid) {
+        return if order.order_creation.partially_fillable {
+            // TODO - driver logic for Partially Fillable Orders
+            // https://github.com/gnosis/gp-v2-services/issues/673
+            tracing::error!("filtering partially fillable inflight orders unimplemented.");
+            Some(order)
```
Comment (nlordell) [inline solver/src/liquidity/offchain_orderbook.rs:46]: I really like this pragmatic approach we settled on.

File: solver/src/liquidity/offchain_orderbook.rs [hunk 12]
```diff
@@ -312,4 +338,44 @@ pub mod tests {
             },
         );
     }
+
+    #[test]
+    fn inflight_order_filter_() {
```
Comment (nlordell) [inline solver/src/liquidity/offchain_orderbook.rs:343]: Nice! Love the test

File: solver/src/liquidity/offchain_orderbook.rs (hunk 10 above)
Comment (bh2smith) [reply solver/src/liquidity/offchain_orderbook.rs:37]: I am totally fine with this approach. I was just trying to address Felix's comment (https://github.com/gnosis/gp-v2-services/pull/662#discussion_r642221566). Will revert to just a `HashSet<OrderUid>` for now then.

File: solver/src/settlement.rs [hunk 13]
```diff
@@ -13,7 +13,7 @@ use std::collections::HashMap;
 
 pub use settlement_encoder::SettlementEncoder;
 
-#[derive(Clone, Debug, Default, Eq, PartialEq)]
+#[derive(Clone, Debug, Default, Eq, Hash, PartialEq)]
```
Comment (bh2smith) [inline solver/src/settlement.rs:16]:
```suggestion
#[derive(Clone, Debug, Default, Eq, PartialEq)]
```

File: solver/src/liquidity/offchain_orderbook.rs (hunk 10 above)
Comment (nlordell) [reply solver/src/liquidity/offchain_orderbook.rs]: I added a bunch of comments as to why I don't like `HashSet<Trade>`: https://github.com/gnosis/gp-v2-services/pull/662#discussion_r642390191

File: solver/src/liquidity/offchain_orderbook.rs [hunk 14]
```diff
@@ -28,6 +33,23 @@ struct OrderSettlementHandler {
     order: Order,
 }
 
+fn inflight_order_filter(order: Order, inflight_trades: &HashSet<OrderUid>) -> Option<Order> {
+    // TODO - could model inflight_trades as HashMap<OrderUid, Trade>
```
Comment (nlordell) [inline solver/src/liquidity/offchain_orderbook.rs:37]: I think this might be needed:
```suggestion
    // TODO - could model inflight_trades as HashMap<OrderUid, Vec<Trade>>
```

See comment (https://github.com/gnosis/gp-v2-services/pull/662#discussion_r642393327). This is just a comment, so not really important. Just wanted to point out that partially fillable orders will have some weirdness and hard edge cases when we get around to it.

File: solver/src/driver.rs [hunk 15]
```diff
@@ -334,9 +336,13 @@ impl Driver {
             .await
             .context("failed to get current block")?
             .as_u64();
+
+        let inflight_trades = &self.inflight_trades.clone();
+        // Reset the inflight orders - event if get_liquidity fails.
+        self.inflight_trades = HashSet::new();
```
Comment (nlordell) [inline solver/src/driver.rs:342]: One cool trick you can use to do this more succinctly is:
```suggestion
        let inflight_trades = std::mem::replace(&mut self.inflight_trades, HashSet::new());
```

Which would avoid the `clone`.

Also, I'd like to bring back the point (https://github.com/gnosis/gp-v2-services/pull/662#discussion_r642385489) that I don't think we ever need to clear the inflight trades early. Specifically I think we should just ever clear this on a successful run. So, from line `407`:
```rust
if let Some(mut settlement) = rated_settlements.clone().into_iter().max_by(...) {
    ...
    self.inflight_trades = ...
} else {
    self.inflight_trades = HashSet::new();
}
```
https://github.com/gnosis/gp-v2-services/blob/c368cd97c1d720fd8c508a3c80d29353cdc1e49d/solver/src/driver.rs#L424-L430

With the way it is currently, imagine a situation where:
1. The inflight trades set gets prematurely cleared
2. There is an intermittent network error that causes the fetching the orders to fail
3. Run loops gets restarted right away
4. Orders are fetched containing inflight orders that don't get filtered.

Additionally, I don't even think its a big deal to never clear this - the worse that can happen is the inflight trades become old (but there aren't any new ones), so it would just try to filter out orders that the orderbook API already knows were filled.

Comment (bh2smith) [reply solver/src/driver.rs:342]: Given all these options I would go for the option of not clearing it, but only updating it when necessary. Will wait for @fleupold's input here.

Comment (fleupold) [reply solver/src/driver.rs:342]: The arguments make sense. I can get behind not clearing or only replacing on successful submission.

File: solver/src/liquidity/offchain_orderbook.rs [hunk 16]
```diff
@@ -28,6 +33,23 @@ struct OrderSettlementHandler {
...
 }
 
+fn inflight_order_filter(order: Order, inflight_trades: &HashSet<OrderUid>) -> Option<Order> {
+    // TODO - could model inflight_trades as HashMap<OrderUid, Vec<Trade>>
+    // https://github.com/gnosis/gp-v2-services/issues/673
+    if inflight_trades.contains(&order.order_meta_data.uid) {
+        return if order.order_creation.partially_fillable {
+            // TODO - driver logic for Partially Fillable Orders
+            // https://github.com/gnosis/gp-v2-services/issues/673
+            tracing::error!("filtering partially fillable inflight orders unimplemented.");
```
Comment (fleupold) [inline solver/src/liquidity/offchain_orderbook.rs:43]: nano nit: I wouldn't log an error in this case. The worst case that could happen is that our simulation fails due to order filled in which case it would already notify us.

File: solver/src/liquidity/offchain_orderbook.rs [hunk 17]
```diff
@@ -28,6 +33,23 @@ struct OrderSettlementHandler {
     order: Order,
 }
 
+fn inflight_order_filter(order: Order, inflight_trades: &HashSet<OrderUid>) -> Option<Order> {
```
Comment (fleupold) [inline solver/src/liquidity/offchain_orderbook.rs:36]: The signature is already designed to later on mutate partially fillable orders? Otherwise a simple bool filter would suffice (but it makes sense to already set this up like that).

**Review by fleupold — APPROVED** [review]
LGTM

File: solver/src/driver.rs (hunk 15 above)
Comment (bh2smith) [reply solver/src/driver.rs:342]: I will go with that then!

File: solver/src/liquidity/offchain_orderbook.rs (hunk 17 above)
Comment (bh2smith) [reply solver/src/liquidity/offchain_orderbook.rs:36]: Yes, this was the purpose of the function signature. Good eye!

**Review by nlordell — APPROVED** [review]
