### PR TITLE
Fix div by zero

### LINKED ISSUE #420: Divide by 0 panic computing objective value
We encountered the following panic computing the objective value:
```
ERROR (pod: dev-dfusion-v2-solver-rinkeby-85d5b74797-mvvmk):
2021-03-26T15:05:43.197Z ERROR shared::tracing: thread 'main' panicked at 'attempt to divide by zero', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.0/src/biguint/division.rs:160:9:
  0: std::panicking::begin_panic
  1: num_bigint::biguint::division::div_rem_ref
  2: num_bigint::bigint::division::<impl core::ops::arith::Div for num_bigint::bigint::BigInt>::div
  3: <num_rational::Ratio<T> as core::ops::arith::Div>::div
  4: solver::settlement::Settlement::objective_value
  5: solver::driver::Driver::single_run::{{closure}}
  6: solver::main::{{closure}}
  7: tokio::runtime::enter::Enter::block_on
  8: tokio::runtime::thread_pool::ThreadPool::block_on
  9: tokio::runtime::context::enter
 10: tokio::runtime::handle::Handle::enter
 11: solver::main
```

### PR DESCRIPTION
**Pull request by marcovc**
Closes #420 .

Added test case.

### CODE REVIEW

**Comment by marcovc** [comment]
Note: The MIP solver is not supposed to generate zero prices. I guess the other two should be investigated for this case as well.

File: solver/src/settlement.rs [hunk 1]
```diff
@@ -140,6 +140,13 @@ impl Settlement {
                 .get(&trade.order.buy_token)
                 .expect("Solution with trade but without price for buy token");
 
+            if trade.order.kind == OrderKind::Sell && buy_token_clearing_price.is_zero() {
+                return None;
+            }
+            if trade.order.kind == OrderKind::Buy && sell_token_clearing_price.is_zero() {
+                return None;
+            }
```
Comment (vkgnosis) [inline solver/src/settlement.rs:148]: Another way to write this could be

```suggestion
            if match trade.order.kind {
                OrderKind::Buy => &sell_token_clearing_price,
                OrderKind::Sell => &buy_token_clearing_price,
            }
            .is_zero()
            {
                return None;
            }

```

I like that because it uses match which I find clearer than if because it makes it obvious that the branches are exclusive and that all enum cases are handled. Either way is fine, just wanted to suggest it.

**Review by vkgnosis — APPROVED** [review]
Looks good. Agree that zero prices don't make sense and other solvers shouldn't be emitting them. Maybe something we can eventually enforce on the Settlement struct.

**Review by fleupold — APPROVED** [review]
I wonder if instead of using these one-off 0 checks, we should rather start using checked_div whenever we divide and then just `?` at the end.

**Review by bh2smith — APPROVED** [review]

File: solver/src/settlement.rs (hunk 1 above)
Comment (marcovc) [reply solver/src/settlement.rs]: Cool, thanks!
