### PR TITLE
Respected Execution Plan Ordering

### LINKED ISSUE #889: Respect Execution Plan for HTTP Solver when mixing Weighted and Constant Pools
The following settlement failed simulation: https://dashboard.tenderly.co/gp-v2/staging/simulator/3382be4f-81b0-42e3-b5ff-37da31926433

We can see that we first try to interact with Uniswap but the settlement contract doesn't have enough sell balance for that:

image

The execution plan of the MiP [solver's solution file](http://gnosis-europe-gpv2-solver.s3-eu-central-1.amazonaws.com/data/prod/2021/07/23/17%3A36%3A56.846593354_UTC_Ethereum_1/05_solution_int.json) shows that we should have first interacted with the weighted balancer pool and then invoked the constant product pool.

Checking the code in the HTTP solver we only respect the execution plan within each group of pools but not across pools:

https://github.com/gnosis/oba-services/blob/9b409b1d2de22fcaa63adf601c9dce61ddc51697/solver/src/solver/http_solver/settlement.rs#L162-L163

Therefore we always execute all constant product interactions first.

### PR DESCRIPTION
**Pull request by bh2smith**
Fixes #889

Previously we had been losing the execution plan ordering by returning two separate vectors of executed Amms. Now, however, we return a single vector of a new enum which holds both types of executed amms.

### Test Plan
Existing tests adapted to new types.

### CODE REVIEW

File: solver/src/solver/http_solver/settlement.rs [hunk 1]
```diff
@@ -54,18 +53,26 @@ impl ExecutedLimitOrder {
...
+struct ExecutedWeightedProductAmm {
     order: WeightedProductOrder,
     input: (H160, U256),
     output: (H160, U256),
 }
 
+#[derive(Clone, Debug)]
+enum ExecutedAmm {
+    CP(ExecutedConstantProductAmm),
+    WP(ExecutedWeightedProductAmm),
```
Comment (vkgnosis) [inline solver/src/solver/http_solver/settlement.rs:73]: We could move the whole struct declaration here instead of keeping it separate:

```rust
enum ExecutedAmm {
    ExecutedConstantProductAmm {
        ...
    },
    ExecutedWeightedProductAmm { ... }
}
```

Not necessary just something I noticed because we never use the structs standalone.

Comment (bh2smith) [reply solver/src/solver/http_solver/settlement.rs:73]: Cool, I wasn't aware of this! Will give it a try.

Comment (vkgnosis) [reply solver/src/solver/http_solver/settlement.rs:73]: Alternatively you could do this:

```rust
struct ExecutedAmm {
    input: (H160, U256),
    output: (H160, U256),
    order: ExecutedOrder
}

enum ExecutedOrder {
    ConstantProduct(ConstantProductOrder),
    WeightedProduct(WeightedProductOrder),
}
```

Which would help with your comment below that you need identical code in two match branches. With this struct input and output are always available.

File: solver/src/solver/http_solver/settlement.rs [hunk 2]
```diff
@@ -201,12 +206,18 @@ fn match_settled_prices(
         .flat_map(|order| {
             iter::once(order.order.buy_token).chain(iter::once(order.order.sell_token))
         })
-        .chain(executed_amms.0.iter().flat_map(|amm| amm.order.tokens))
         .chain(
             executed_amms
-                .1
                 .iter()
-                .flat_map(|amm| amm.order.reserves.keys().copied().collect::<Vec<H160>>()),
```
Comment (vkgnosis) [inline solver/src/solver/http_solver/settlement.rs:209]: I know this was already here and isn't related to this PR but I'm wondering now if it is correct that the prices hashmap we return from this function contains all of the reserve keys? Doesn't this only need to contain the prices from limit orders because those are what the smart contract needs?

File: solver/src/solver/http_solver/settlement.rs (hunk 1 above)
Comment (bh2smith) [reply solver/src/solver/http_solver/settlement.rs:73]: I had also tried this in the past, but there was something about it that wasn't working well. However I will try your second suggestion now. Since I am having trouble accessing the fields of the structs with your first suggestion.

File: solver/src/solver/http_solver/settlement.rs (hunk 2 above)
Comment (bh2smith) [reply solver/src/solver/http_solver/settlement.rs:209]: Great point. I will check this out!

**Review by vkgnosis — APPROVED** [review]

File: solver/src/solver/http_solver/settlement.rs (hunk 2 above)
Comment (bh2smith) [reply solver/src/solver/http_solver/settlement.rs:209]: So, given the function signature
```rust
fn match_settled_prices(
    executed_limit_orders: &[ExecutedLimitOrder],
    executed_amms: &[ExecutedAmm],
    solver_prices: HashMap<H160, Price>,
) -> Result<HashMap<H160, U256>> {
```

It would be possible to get the tokens from the Limit order however, I suspect we might run into issues where the execution plan routes though a token which is not included in the limit orders.

On the other hand, we shouldn't need to supply prices for these amm-only tokens, so I will create a separate issue for this and experiment with it in a following PR.

Comment (bh2smith) [reply solver/src/solver/http_solver/settlement.rs:209]: Issue filed here: #892

**Review by fleupold — APPROVED** [review]
Looks good. Can we maybe add a unit test (or adopt the existing one that is verifying the execution plan is respected) in a way that would have failed before this PR?

**Comment by bh2smith** [comment]
> Can we maybe add a unit test (or adopt the existing one that is verifying the execution plan is respected) in a way that would have failed before this PR?

I believe the existing test that was adapted does indeed show that that ordering is respected (note the change of index in the unit test case and how the `wp_order` comes before the `cp_order`).

**Comment by fleupold** [comment]
> I believe the existing test that was adapted does indeed show that that ordering is respected

I think it would be slightly more robust to test that mixing and matching execution plans (e.g. Weighted, Constant, Weighted, Constant) works as expected. In order to make the existing test code pass all we would have to do is process weighted pools before constant pools (but not actually fix the logic).

But not a big deal.

**Comment by bh2smith** [comment]
> test that mixing and matching execution plans (e.g. Weighted, Constant, Weighted, Constant) works as expected.

I can try and come up with something for this in a follow up.

> ... all we would have to do is process weighted pools before constant pools (but not actually fix the logic).

Not sure I follow your thought process here.

**Comment by fleupold** [comment]
> Not sure I follow your thought process here.

In test driven development you usually try to make the smallest possible change in order to make the failing test pass. In the current regression test the smallest change to make it pass would have been to inverse the order in which we add constant/weighted interactions to the execution plan. This would not fix the logic. As a long shot if in some later refactoring someone reverts this change and they coincidentally process the weighted pools before the constant ones no test would fail.

Not a big deal and kind of a long shot but just wanted to point out that the regression test could be stronger.

**Comment by bh2smith** [comment]
I still think that including those match statements on the amm order types is a small change that would have failed with the big we just addressed.
