### PR TITLE
Fix handling of buy order edge case in baseline solver

### LINKED ISSUE #1140: Investigate panic
We had to hotfix the unwrap in `solver/src/solver/baseline_solver.rs` `expect("Path was found, so amount must be calculable")` because it got triggered on prod mainnet.
The first panic was at `2021-09-21T13:56:11.336Z`. 

<details>

```
2021-09-21T13:56:11.336Z ERROR shared::tracing: thread 'main' panicked at 'Path was found, so amount must be calculable', solver/src/solver/baseline_solver.rs:266:18:

thread 'main' panicked at 'Path was found, so amount must be calculable', solver/src/solver/baseline_solver.rs:266:18

stack backtrace:

   0: rust_begin_unwind

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5

   1: core::panicking::panic_fmt

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14

   2: core::option::expect_failed

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:1578:5

   3: core::option::Option<T>::expect

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:685:21

   4: solver::solver::baseline_solver::Solution::into_settlement

             at ./usr/src/oba-services/solver/src/solver/baseline_solver.rs:264:30

   5: solver::solver::baseline_solver::BaselineSolver::solve

             at ./usr/src/oba-services/solver/src/solver/baseline_solver.rs:193:23

   6: <solver::solver::baseline_solver::BaselineSolver as solver::solver::Solver>::solve::{{closure}}

             at ./usr/src/oba-services/solver/src/solver/baseline_solver.rs:42:12

   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19

   8: <core::pin::Pin<P> as core::future::future::Future>::poll

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/future.rs:119:9

   9: <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/time/timeout.rs:149:33

  10: solver::driver::Driver::run_solvers::{{closure}}::{{closure}}::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:124:27

  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19

  12: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.17/src/future/maybe_done.rs:95:38

  13: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.17/src/future/join_all.rs:143:24

  14: solver::driver::Driver::run_solvers::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:118:9

  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19

  16: solver::driver::Driver::single_run::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:405:34

  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19

  18: solver::driver::Driver::run_forever::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:104:19

  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19

  20: solver::main::{{closure}}

             at ./usr/src/oba-services/solver/src/main.rs:485:5

  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19

  22: tokio::park::thread::CachedParkThread::block_on::{{closure}}

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/park/thread.rs:263:54

  23: tokio::coop::with_budget::{{closure}}

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:106:9

  24: std::thread::local::LocalKey<T>::try_with

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:399:16

  25: std::thread::local::LocalKey<T>::with

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:375:9

  26: tokio::coop::with_budget

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:99:5

  27: tokio::coop::budget

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:76:5

  28: tokio::park::thread::CachedParkThread::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/park/thread.rs:263:31

  29: tokio::runtime::enter::Enter::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/enter.rs:151:13

  30: tokio::runtime::thread_pool::ThreadPool::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/mod.rs:72:9

  31: tokio::runtime::Runtime::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/mod.rs:459:43

  32: solver::main

             at ./usr/src/oba-services/solver/src/main.rs:485:5

  33: core::ops::function::FnOnce::call_once

             at ./rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
```

</details>

The most recently created order at that point was [this](https://protocol-mainnet.gnosis.io/api/v1/orders/0xbbdce25e9fa28463075609ca9578ca94788a18f4d9f959e688e20cf45507c013663209723924567f58017dbbc87f35c52aed6db16149eacf) .

<details>

```json
{
  "creationDate": "2021-09-21T13:55:49.471868Z",
  "owner": "0x663209723924567f58017dbbc87f35c52aed6db1",
  "uid": "0xbbdce25e9fa28463075609ca9578ca94788a18f4d9f959e688e20cf45507c013663209723924567f58017dbbc87f35c52aed6db16149eacf",
  "availableBalance": null,
  "executedBuyAmount": "0",
  "executedSellAmount": "0",
  "executedSellAmountBeforeFees": "0",
  "executedFeeAmount": "0",
  "invalidated": false,
  "status": "expired",
  "settlementContract": "0x9008d19f58aabd9ed0d60971565aa8510560ab41",
  "sellToken": "0xdac17f958d2ee523a2206206994597c13d831ec7",
  "buyToken": "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
  "receiver": "0x663209723924567f58017dbbc87f35c52aed6db1",
  "sellAmount": "39156155933",
  "buyAmount": "12873053417182804593",
  "validTo": 1632234191,
  "appData": "0x487b02c558d729abaf3ecf17881a4181e5bc2446429a0995142297e897b6eb37",
  "feeAmount": "16270298",
  "kind": "sell",
  "partiallyFillable": false,
  "signingScheme": "eip712",
  "signature": "0x8cb9e15dd894f00fbf978a56031128110fa46daf837cc8898aef31cf98cc72b868cad0686cfa62a3bbdbab23019385efdec0a72bcb9dcf11dd5183da75ed44741b",
  "sellTokenBalance": "erc20",
  "buyTokenBalance": "erc20"
}
```

</details>

Other solvabe orders during the crash were:

<details>

```
0x0b27324244b90761c05c08ac8417587cfe41e1412dbe14be0f664a1ea2d8ba11e63a13eedd01b624958acfe32145298788a7a7ba6149e4ee,
0x69d1d2ac2d71692d6ea5221a972305f9a3767ae6e5199efb511d8f5ad57743dae63a13eedd01b624958acfe32145298788a7a7ba6149e4ee,
0xe7a0f149236095aa428c274ea4c8018483c4f146b007ac535e21bcc4b49ad457e63a13eedd01b624958acfe32145298788a7a7ba6149e4e3,
0x52245bed0ee9b195b5633bb1b5266f6b6d7a1e3ada13a870e6a4bf1540db7aabe63a13eedd01b624958acfe32145298788a7a7ba6149e4e3,
0x0cf0535e6a61885a73ee9c0f6fd4ece12f56937103fab05166f53b77031a0980e63a13eedd01b624958acfe32145298788a7a7ba6149e4cd,
0x546e65ac59d85e5e924c9b4d858cc1118b9d60a979c7c10de56f664666d49caae63a13eedd01b624958acfe32145298788a7a7ba6149e4cd,
0x510728d50d6ffe45861f01c373e00f028a10f3df7f2d1a9518998ec5a2c8e678e63a13eedd01b624958acfe32145298788a7a7ba6149e4c3,
0xbd8ddce17793f5db9f2d49e315b72498cf14675aa6d1bb74f392e6f930d18b7fe63a13eedd01b624958acfe32145298788a7a7ba6149e4c3,
0x6fc672944fb39dcfc956c032a53ce19dcf99eb1965c9686a42fb6c0d017ac3c4e34884d8be46f1807a62d008c35a4e2afa64191d6149eae8,
0x6a8aa76e2c26c18a303b2f25f87076b78219bf5daa7c01a88aa9b03ec52c96bd54e5e90a6679314e8339bb1ed74beab5ca19324a6149eb19,
0x055a211b30d3d4bbeaee95f66b1d255a044474ab33b4bb4eb73fedcb67fa9861cbf5cf96fd7f2ac026bf35d6bb577c79e1ebb4a46149eb08,
0xc75689c8a8ddb6ae98c12e6c32cf100d6d773f81187d4e03c96edf3c17fdb69c960ce1c1dbb2085e387b84d7fb0d163a1b4eaa1c6149eb4a,
0x464b7ac3f13408efad2945f797bf8c58f39858faa78329aaa82dd2f42d37d40fdeeb758e147ea422e6bad89bcfafabfac05279496149e896,
0x9e9f5d3ef5c6b3c5e12c8bc9719858c12458b5e8af163429c7f2e8857b413349e63a13eedd01b624958acfe32145298788a7a7ba6149e4ed,
0xbbdce25e9fa28463075609ca9578ca94788a18f4d9f959e688e20cf45507c013663209723924567f58017dbbc87f35c52aed6db16149eacf
```

</details>

We still need to investigate why this got triggered and fix this on main as the hotfix was only applied to the new tag.

### PR DESCRIPTION
**Pull request by vkgnosis**
To find the optimal path for buy orders we start at the buy token and
use get_amount_in repeatedly until we arrive at the sell token. However
when creating a settlement the path has to be traversed in the sell
direction because that is what the user has balance in.
This is problematic when an amm is not symmetrical: using the result of
get_amount_in in get_amount_out returns a (usually slightly) different
value. This can cause further amm interactions to fail.
This commit fixes this by enforcing the forward (sell) direction of the
resulting paths for buy orders. Sell orders do not need to be fixed as
they are already in the correct direction.
Additionally I have moved order limit checks into settle_order because
it felt more natural there with the forward path check.

Closes #1140

### Test Plan
Existing tests. I would have like to add a test for the panic case too but was unable to do so because the way the types are specified in the baseline solver I cannot easily pass in my own `impl BaselineSolvable` that has the behavior I want. So I would have to craft a pool that showcases this behavior by hand which was too time consuming.

### CODE REVIEW

**Review by nlordell — APPROVED** [review]

File: shared/src/sources/balancer/swap.rs [hunk 1]
```diff
@@ -123,26 +112,15 @@ impl WeightedPoolRef<'_> {
...
-        // We double check that resulting amount out can symmetrically provide an amount in.
-        self.unchecked_get_amount_in(in_token, (out_amount, out_token))?;
-        Some(out_amount)
-    }
 }
 
 impl BaselineSolvable for WeightedPoolRef<'_> {
     fn get_amount_out(&self, out_token: H160, (in_amount, in_token): (U256, H160)) -> Option<U256> {
-        self.checked_get_amount_out(out_token, (in_amount, in_token))
+        self.get_amount_out_(out_token, (in_amount, in_token))
```
Comment (nlordell) [inline shared/src/sources/balancer/swap.rs:119]: ~~nit: Not a huge fan of having the method name the exact same as the trait name, as it makes it harder to see which one is being called without additional context.~~

**edit**: Oops, missed the sneaky `_`.

Comment (bh2smith) [reply shared/src/sources/balancer/swap.rs:119]: Even with the `_`, it doesn't really highlight the fact that it is "checked". Either way, I guess this is fine. Although I kinda liked the name "checked_*"

File: shared/src/sources/balancer/swap.rs [hunk 2]
```diff
@@ -123,26 +112,15 @@ impl WeightedPoolRef<'_> {
...
-    fn checked_get_amount_out(
-        &self,
-        out_token: H160,
-        (in_amount, in_token): (U256, H160),
-    ) -> Option<U256> {
-        let out_amount = self.unchecked_get_amount_out(out_token, (in_amount, in_token))?;
-        // We double check that resulting amount out can symmetrically provide an amount in.
-        self.unchecked_get_amount_in(in_token, (out_amount, out_token))?;
-        Some(out_amount)
-    }
```
Comment (bh2smith) [inline shared/src/sources/balancer/swap.rs:136]: I see that these were removed in favour of `get_amount_*_`, but it doesn't appear they were actually re-implemented somewhere else... what happened with `unchecked_get_amount_*` is it even used anymore? Based on the changes here, I can only assume that we already had `get_amount_out_` and it was implemented identical to this method here that was removed.

**Review by bh2smith — APPROVED** [review]
Cool stuff.

File: shared/src/baseline_solver.rs [hunk 3]
```diff
@@ -10,6 +10,11 @@ const DEFAULT_MAX_HOPS: usize = 2;
 
 type PathCandidate = Vec<H160>;
 
+/// Note that get_amount_out and get_amount_in are not always symmetrical. That is for some AMMs it
+/// is possible that get_amount_out returns an amount for which get_amount_in returns None when
+/// trying to go the reverse direction. Or that the resulting amount is different from the original.
+/// This situation is rare and resulting amounts should usually be identical or very close but it
+/// can occur.
```
Comment (bh2smith) [inline shared/src/baseline_solver.rs:17]: Could we, perhaps, introduce a unit test which demonstrates that these scenarios described are indeed possible? It would help me and the reader to have a sense of when this can happen? My only guess at the moment (if this is rare) would be when pool reserves are very low on one side and very high on the other... Or possibly when the amount in is greater than the reserves the pool currently holds of that token.

File: solver/src/solver/baseline_solver.rs [hunk 4]
```diff
@@ -210,13 +205,28 @@ impl BaselineSolver {
...
+                    // sell token. When we turn this into a settlement however we need to go from
+                    // the sell token to the buy token. This reversing of the direction can fail or
+                    // yield different amounts as explained in the BaselineSolvable trait.
+                    .filter(|estimate| {
+                        matches!(
+                            traverse_path_forward(
+                                order.sell_token,
+                                estimate.value,
+                                &estimate.path,
+                            ), Some(amount) if amount >= order.buy_amount
```
Comment (fleupold) [inline solver/src/solver/baseline_solver.rs:219]: Is this check really necessary? Wouldn't - if the computed buy amount was slightly lower than the order buy amount - the remainder just be filled from our internal balances as long as the prices announced in the solution satisfy the user's limit price?

Also, wouldn't the equivalent of checking `estimate.value >= order.buy_amount` below, be verifying that ` `estimate.value <= order.sell_amount` here (but I assume this limit price check is also done somewhere else)?

File: shared/src/baseline_solver.rs (hunk 3 above)
Comment (fleupold) [reply shared/src/baseline_solver.rs:17]: My assumption is that this is possible if the traded amounts are very small (e.g. 1wei). In this case out amount may return 0 or one, while get_amount_in for that value returns None.

Agree that a unit test demonstrating the issue for one specific Pool would be a nice way of improving our understanding of it.

File: shared/src/sources/balancer/swap.rs (hunk 1 above)
Comment (nlordell) [reply shared/src/sources/balancer/swap.rs:119]: My issue with the name `checked_` is that its quite ambiguous about what is checked. Additionally, both functions have the same signature and return an `Option`.

File: solver/src/solver/baseline_solver.rs (hunk 4 above)
Comment (vkgnosis) [reply solver/src/solver/baseline_solver.rs:219]: `traverse_path_forward` succeeding is necessary.  `estimate.value <= order.sell_amount` is the equivalent of what happens for OrderKind::Sell. Here it happens in the line above this `.filter` (but hard to spot in the diff, i managed to miss it at first now too and thought i hadn't committed it).
I still think it makes sense to also have `amount >= order.buy_amount` as we are supposed to produce a correct settlement here which should work even without buffers.

File: shared/src/baseline_solver.rs (hunk 3 above)
Comment (fleupold) [reply shared/src/baseline_solver.rs:17]: On this note (I forgot if I mentioned this somewhere last week), maybe it would make sense to reintroduce fuzzing to components like the BaselineSolver. That would likely find example cases quite easily

**Comment by vkgnosis** [comment]
I've added a test to highlight this problem. See the new unit test at the bottom of the file.
