### PR TITLE
[Balancer] BaselineSolvable - Check in/out amounts can be reciprocated

### LINKED ISSUE #838: Baseline solver panicking with buy orders.
It appears that the Baseline solver is still panicking with buy orders.

<details><summary>Stack trace:</summary>

```
thread 'main' panicked at 'Path was found, so amount must be calculateable', solver/src/solver/baseline_solver.rs:215:18:

   0: rust_begin_unwind

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5

   1: core::panicking::panic_fmt

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14

   2: core::option::expect_failed

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:1241:5

   3: core::option::Option<T>::expect

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:349:21

   4: solver::solver::baseline_solver::Solution::into_settlement

             at ./usr/src/oba-services/solver/src/solver/baseline_solver.rs:213:30

   5: solver::solver::baseline_solver::BaselineSolver::solve

             at ./usr/src/oba-services/solver/src/solver/baseline_solver.rs:142:23

   6: <solver::solver::baseline_solver::BaselineSolver as solver::solver::Solver>::solve::{{closure}}

             at ./usr/src/oba-services/solver/src/solver/baseline_solver.rs:35:12

   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

   8: <core::pin::Pin<P> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/future.rs:120:9

   9: <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/time/timeout.rs:149:33

  10: solver::driver::Driver::run_solvers::{{closure}}::{{closure}}::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:123:36

  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

  12: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/maybe_done.rs:95:38

  13: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/join_all.rs:97:16

  14: solver::driver::Driver::run_solvers::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:118:9

  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

  16: solver::driver::Driver::single_run::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:376:27

  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

  18: solver::driver::Driver::run_forever::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:104:19

  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

  20: solver::main::{{closure}}

             at ./usr/src/oba-services/solver/src/main.rs:363:5

  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

  22: tokio::park::thread::CachedParkThread::block_on::{{closure}}

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/park/thread.rs:263:54

  23: tokio::coop::with_budget::{{closure}}

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/coop.rs:106:9

  24: std::thread::local::LocalKey<T>::try_with

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16

  25: std::thread::local::LocalKey<T>::with

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9

  26: tokio::coop::with_budget

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/coop.rs:99:5

  27: tokio::coop::budget

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/coop.rs:76:5

  28: tokio::park::thread::CachedParkThread::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/park/thread.rs:263:31

  29: tokio::runtime::enter::Enter::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/runtime/enter.rs:151:13

  30: tokio::runtime::thread_pool::ThreadPool::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/runtime/thread_pool/mod.rs:71:9

  31: tokio::runtime::Runtime::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/runtime/mod.rs:452:43

  32: solver::main

             at ./usr/src/oba-services/solver/src/main.rs:363:5

  33: core::ops::function::FnOnce::call_once

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
```

</details>

### PR DESCRIPTION
**Pull request by nlordell**
Closes #838

We implement a form of "checked_get_amount_in/out" which is essentially the content of the original "get_amount_in/out
" trait methods for baseline solvable which take in a boolean flag `check_reciprocal` that (in order to avoid infinite recursion) called the diametrically opposite method with the resulting value when `check_reciprocal == true`. We perform the checked implementation on the first call, but when checking pass `false`. 

Test is now passing!

### UPDATE (bh2smith)

Based on the discussion in the corresponding issue we now check that in and out amounts are "good" if the reverse out and in amounts can be computed from them. These changes demonstrate that the failing test here is now passing.

### CODE REVIEW

File: shared/src/sources/balancer/swap.rs [hunk 1]
```diff
@@ -63,49 +63,93 @@ impl WeightedPoolRef<'_> {
...
+        in_token: H160,
+        (out_amount, out_token): (U256, H160),
+    ) -> Option<U256> {
+        // We double check that resulting amount in can symmetrically provide an amount out.
+        if let Some(in_amount) = self.unchecked_get_amount_in(in_token, (out_amount, out_token)) {
+            return self
+                .unchecked_get_amount_out(out_token, (in_amount, in_token))
+                .map(|_| in_amount);
+        };
+        None
```
Comment (nlordell) [inline shared/src/sources/balancer/swap.rs:103]: This can be written more succinctly as:
```suggestion
        if in_amount = self.unchecked_get_amount_in(in_token, (out_amount, out_token))?;
        // We double check that resulting amount in can symmetrically provide an amount out.
        self.unchecked_get_amount_out(out_token, (in_amount, in_token))?;
        Some(in_amount)
```

Comment (bh2smith) [reply shared/src/sources/balancer/swap.rs:103]: I didn't realize the ? Operator worked on Option. Will try it out tomorrow morning.

**Review by vkgnosis — APPROVED** [review]

**Review by bh2smith — APPROVED** [review]
