### PR TITLE
[Easy] Propogate EventHandler Maintenance Failure Logs

### LINKED ISSUE #656: Maintenance Error description poorly propogated
We have a long list of recent errors all with minimal information that can't really be debugged.

```
2021-05-26T13:39:06.906Z ERROR shared::maintenance: failed with: event update error
2021-05-26T13:39:44.212Z ERROR shared::maintenance: failed with: event update error
2021-05-26T13:41:20.116Z ERROR shared::maintenance: failed with: event update error
2021-05-26T13:43:43.687Z ERROR shared::maintenance: failed with: event update error
2021-05-26T13:45:54.731Z ERROR shared::maintenance: failed with: event update error
2021-05-26T13:47:12.868Z  WARN shared::current_block: failed to get current block: failed to get current block
Caused by:
    0: RPC error: Error { code: InternalError, message: "request failed or timed out", data: None }
    1: Internal error: request failed or timed out
2021-05-26T13:48:20.740Z ERROR shared::maintenance: failed with: event update error
2021-05-26T13:49:24.940Z ERROR shared::maintenance: failed with: event update error
2021-05-26T13:49:58.469Z ERROR shared::maintenance: failed with: event update error
```

Given that maintenance is run in several different places, it might be valuable to provide a more descriptive error message.

### PR DESCRIPTION
**Pull request by bh2smith**
Fixes #656
Attempting to propagate a more descriptive error out of failed `EventHandler` maintenance. Currently we are getting:

```
shared::maintenance: failed with: event update error
```

Note that this is also being emitted from the other file that was touched which has been updated a bit to be more specific

So, what we would expect to see now for similar occurrences of an error could be any of 

```
shared::maintenance: Service Maintenance Error: failed to get past events
shared::maintenance: Service Maintenance Error: failed to get next chunk of events
shared::maintenance: Service Maintenance Error: replace - failed to convert events
shared::maintenance: Service Maintenance Error: append - failed to convert events
shared::maintenance: Service Maintenance Error: failed to insert trades
shared::maintenance: Service Maintenance Error: failed to replace trades
```

and possibly more.

### Test Plan
This trait implementation for `Mutex<EventHandler<B, C, S>>` seems like quite an elaborate construct I am not sure if it can easily be mocked. Happy to try if reviewers think it should be.

### CODE REVIEW

File: shared/src/event_handling.rs [hunk 1]
```diff
@@ -170,11 +170,7 @@ where
     S: EventStoring<C::Event> + Send + Sync,
 {
     async fn run_maintenance(&self) -> Result<()> {
-        self.lock()
-            .await
-            .update_events()
-            .await
-            .context("event update error")
```
Comment (bh2smith) [inline shared/src/event_handling.rs:177]: This is the 🔑  change to avoid over generalizing the error message and losing track of what really happened.

File: shared/src/event_handling.rs [hunk 2]
```diff
@@ -170,11 +170,7 @@ where
...
+        self.lock().await.update_events().await
```
Comment (bh2smith) [inline shared/src/event_handling.rs:173]: This is the 🔑  change to propagate internal errors better

**Review by vkgnosis — APPROVED** [review]

File: shared/src/maintenance.rs [hunk 3]
```diff
@@ -19,7 +19,7 @@ impl Maintaining for ServiceMaintenance {
     async fn run_maintenance(&self) -> Result<()> {
         for result in join_all(self.maintainers.iter().map(|m| m.run_maintenance())).await {
             if let Err(err) = result {
-                tracing::error!("failed with: {}", err);
+                tracing::error!("Service Maintenance Error: {}", err);
```
Comment (vkgnosis) [inline shared/src/maintenance.rs:22]: For our anyhow errors it is a little better to use the `{:?}` format string than `{}` here because it sometimes includes more relevant information.

Comment (bh2smith) [reply shared/src/maintenance.rs:22]:
```suggestion
                tracing::error!("Service Maintenance Error: {:?}", err);
```

File: shared/src/event_handling.rs (hunk 2 above)
Comment (fleupold) [reply shared/src/event_handling.rs:173]: Isn't this only removing one layer of context? Wouldn't it without the change below now just say 

`shared::maintenance: failed with: replace - failed to convert events`

which still wouldn't tell you much about what's happening?

File: shared/src/maintenance.rs [hunk 4]
```diff
@@ -19,7 +19,7 @@ impl Maintaining for ServiceMaintenance {
     async fn run_maintenance(&self) -> Result<()> {
         for result in join_all(self.maintainers.iter().map(|m| m.run_maintenance())).await {
             if let Err(err) = result {
-                tracing::error!("failed with: {}", err);
+                tracing::error!("Service Maintenance Error: {:?}", err);
```
Comment (fleupold) [inline shared/src/maintenance.rs:22]: As far as my understanding goes, this is the key change, which will make us log the entire error chain instead of just the top level context.

File: shared/src/event_handling.rs (hunk 2 above)
Comment (nlordell) [reply shared/src/event_handling.rs:173]: I think the other key change is :point_down: where we use the debug instead of display formatter to print the error, thereby printing the entire error chain and not the most recent context (as you also noted).

File: shared/src/maintenance.rs (hunk 4 above)
Comment (bh2smith) [reply shared/src/maintenance.rs:22]: Good to know!

File: shared/src/event_handling.rs (hunk 2 above)
Comment (bh2smith) [reply shared/src/event_handling.rs:173]: Looking forward to running into these errors again! Will be ready for them now.
