### PR TITLE
[Easy] Update or reset inflight trades based on submission result

### LINKED ISSUE #791: Orders are added to inflight trades even if settlement is not successful
https://github.com/gnosis/gp-v2-services/blob/6a500707a041eea0bc178618eb05fcf84fcdb09c/solver/src/driver.rs#L434-L442

This means we won't attempt to resettle orders in the next runloop if their execution has failed. Moreover, if the next runloop doesn't produce any solution, we won't enter the `if` statement in which `inflight_order` would be reset. Thus it is possible to completely "ignore" this order going forward.

To fix this `submit_settlement` should probably return information as to whether the settlement was successful and inflight trades should be reset unconditionally.

### PR DESCRIPTION
**Pull request by bh2smith**
Closes #791

As described in the related issue, inflight trades could be populated with orders even if submission fails and also not reset if the next run loop fails to find a solution. This PR makes the update of inflight trades dependent on the submission Result.

### Test Plan
Existing CI.

### CODE REVIEW

File: solver/src/driver.rs [hunk 1]
```diff
@@ -431,14 +433,17 @@ impl Driver {
...
+                self.inflight_trades = settlement
+                    .settlement
+                    .settlement
+                    .trades()
+                    .iter()
+                    .map(|t| t.order.order_meta_data.uid)
+                    .collect::<HashSet<OrderUid>>();
+            } else {
+                self.inflight_trades = HashSet::new()
+            }
```
Comment (vkgnosis) [inline solver/src/driver.rs:446]: Instead of creating a new hash set every time we can reuse the existing one which is more efficient.
```suggestion
            self.inflight_trades.clear();
            if self.submit_settlement(settlement.clone()).await.is_ok() {
                self.inflight_trades.extend(
                    settlement
                        .settlement
                        .settlement
                        .trades()
                        .iter()
                        .map(|t| t.order.order_meta_data.uid),
                );
            }
```

**Review by vkgnosis — APPROVED** [review]

**Review by vkgnosis — APPROVED** [review]

File: solver/src/driver.rs (hunk 1 above)
Comment (fleupold) [reply solver/src/driver.rs:446]: Maybe the clear should even happen outside of the `if let Some(mut settlement) = rated_settlements` statement? This way we reset them even if there is no new solution found.

**Review by fleupold — APPROVED** [review]
This logic change would be nice to accompany with a unit test, if that's possible

**Comment by bh2smith** [comment]
> This logic change would be nice to accompany with a unit test, if that's possible

I considered this but I don't believe it was tested in the first place, likely because it will require quite and elaborate setup, but I can give it a try.
