### PR TITLE
[API] Introduction of optional "from" in Order Creation

### LINKED ISSUE #414: [API] allow optional from address parameter on order creation
This would make it easier to debug issues with signature recovery. At the moment, if we provide a slightly incorrect signature (e.g. MSB of `v` not set despite using message encoding) we will recover a valid but random address that has no balance or allowance.

Likely this order is not useful and it makes it hard for the user of the API to realize they are doing something wrong.

An optional fromAddress field on the OrderCreation struct could allow an assertion that the signature resolves to the expected address and otherwise lead to a rejection of the order.

### PR DESCRIPTION
**Pull request by bh2smith**
Fixes #414

Introducing from address as optional parameter for order creation to make it easier to debug when signatures are not valid. This check would not insert orders whose recovered owner that don't match the provided from address.

We also introduce `WrongOwner(address)` error as a response to order creation so to separate this from `InvalidSignature`.

### Test Plan
Existing CLI should suffice (especially the e2e test with ganache demonstrates that the changes are backwards compatible).

### CODE REVIEW

File: model/src/order.rs [hunk 1]
```diff
@@ -159,6 +176,7 @@ pub struct OrderCreation {
     pub partially_fillable: bool,
     pub signature: Signature,
     pub signing_scheme: SigningScheme,
+    pub from: Option<H160>,
```
Comment (fleupold) [inline model/src/order.rs:179]: I don't like that we will carry this field around to all the callsites that should really be using OrderMetadata.owner (from will be sometimes set which might make people believe they could be accessing it).

Maybe we can introduce a new type

```rust
struct OrderCreationPayload {
  #[serde(flatten)]
  pub order_creation: OrderCreation,
  pub from: Option<H160>,
}
```

This way the API would be like currently (flat with an optional from field) but all APIs that return orders would still only return OrderCreation without the From field (which can be read from Metadata)

**Review by fleupold — COMMENTED** [review]
I think this is a good change, however I'd like to avoid carrying this information downstream to all the other call sites using order creation data.

Alternatively we could make it non-optional and remove it from the metadata (however, this would be a breaking change).

File: model/src/order.rs (hunk 1 above)
Comment (bh2smith) [reply model/src/order.rs:168]: I fixed this up according to your suggestion. Looks a lot better now and require less overall changes.

File: orderbook/openapi.yml [hunk 2]
```diff
@@ -40,7 +40,7 @@ paths:
         content:
           application/json:
             schema:
-              $ref: "#/components/schemas/OrderCreation"
+              $ref: "#/components/schemas/OrderCreationPayload"
```
Comment (bh2smith) [inline orderbook/openapi.yml:43]: Isn't this also a breaking change @fleupold ?

Comment (bh2smith) [reply orderbook/openapi.yml]: All good now, I have reverted this to make the changes backwards compatible.

File: orderbook/src/orderbook.rs [hunk 3]
```diff
@@ -79,7 +81,15 @@ impl Orderbook {
             return Ok(AddOrderResult::InsufficientFee);
         }
         let order = match Order::from_order_creation(order, &self.domain_separator) {
-            Some(order) => order,
```
Comment (vkgnosis) [inline orderbook/src/orderbook.rs:82]: I'd like to keep the match on from_order_creation and payload separate because it's easier to read:
This can stay as before:

```rust
        let order = match Order::from_order_creation(order, &self.domain_separator) {
            Some(order) => order,
            None => return Ok(AddOrderResult::InvalidSignature),
        };
```
and then we add either
```rust
        if matches!(payload.from, Some(from) if from != order.order_meta_data.owner) {
            return Ok(AddOrderResult::WrongOwner(order.order_meta_data.owner));
        }
```
or
```rust
        if let Some(from) = payload.from {
            if from != order.order_meta_data.owner {
                return Ok(AddOrderResult::WrongOwner(order.order_meta_data.owner));
            }
        }
```
Not sure which one you find clearer.

**Review by vkgnosis — APPROVED** [review]

File: orderbook/src/orderbook.rs (hunk 3 above)
Comment (bh2smith) [reply orderbook/src/orderbook.rs:82]: Cool! Thanks.

File: orderbook/openapi.yml [hunk 4]
```diff
@@ -384,6 +384,8 @@ components:
           $ref: "#/components/schemas/Signature"
         signingScheme:
           $ref: "#/components/schemas/SigningScheme"
+        from:
+          $ref: "#/components/schemas/Address"
```
Comment (fleupold) [inline orderbook/openapi.yml:388]: nanonit: maybe add nullable (to me this makes it more obvious that the value can be omitted)?

File: orderbook/src/orderbook.rs [hunk 5]
```diff
@@ -82,6 +84,9 @@ impl Orderbook {
             Some(order) => order,
             None => return Ok(AddOrderResult::InvalidSignature),
         };
+        if matches!(payload.from, Some(from) if from != order.order_meta_data.owner) {
```
Comment (fleupold) [inline orderbook/src/orderbook.rs:87]: I guess I'm the only one who has trouble reading these `matches!` statements with `if` blocks inside. Guess, I will learn to cope with them 👨‍🎓

File: model/src/order.rs [hunk 6]
```diff
@@ -162,6 +162,22 @@ pub struct OrderCreation {
...
 }
 
+#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
+pub struct OrderCreationPayload {
+    #[serde(flatten)]
+    pub order_creation: OrderCreation,
+    pub from: Option<H160>,
+}
+
+impl From<OrderCreation> for OrderCreationPayload {
```
Comment (fleupold) [inline model/src/order.rs:172]: Why is this needed? I don't really see the use case for upcasting an order creation to OrderCreationPayload. If this is for the e2e test we should probably provide the `from` address, as this is the first part where this feature will become useful (remember the time you were trying to debug the e2e test because of some signature glitch).

**Review by fleupold — APPROVED** [review]
Looks great!

All backwards compatible and not very intrusive but will be super helpful for debugging 👏

File: model/src/order.rs (hunk 6 above)
Comment (bh2smith) [reply model/src/order.rs:172]: Sorry this was left behind from the change in my last commit before backwards compatibility. Will remove.
